### ISSUE TITLE
Rework Project Scheduling

### ISSUE THREAD

**Issue by nguyendhst** [nguyendhst/HK231-Specialized-Project#12]
- [x] Each release milestone needs feature listing
- [x] Clearer release phases
- [x] Remove Testing
- [x] Report & Documentation need to be included
- [x] Remove old page
- [x] More detailed Task Management

**Comment by FukutoTojido** [comment]
https://semver.org/
- Consider version naming following this format. Since we are still on a development phase, the prototype should be considered as 0.1.0. 
- The next release which is on Nov 5 should not be called a ready-for-production release. Ready-for-production means that we are ready to public its API and everything related for it to be run in a business environment.

**Comment by nguyendhst** [comment]
- The prototype is actually v0.0.1 since it's a preliminary version, not quite a initial release
- Adjusted
